### ISSUE TITLE
Unable to use jsonnet-render

### ISSUE THREAD

**Issue by sudhirkumar05** [alexdglover/jsonnet-render#6]
I am using alexdglover/jsonnet-render@v2 in different ways but the workflow is failing
1. When i create a file after checking out my repository, it doesn't allow me to create the file, it returns permission denied

```
- name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Jsonnet"
        uses: alexdglover/jsonnet-render@v2
        with:
          file: template.jsonnet
          output_file: pipeline-services.yaml
```
 
2. I tried to push the file in /tmp directory but this cannot be used in the next step
```
- name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Jsonnet"
        uses: alexdglover/jsonnet-render@v2
        with:
          file: template.jsonnet
          output_file: /tmp/pipeline-services.yaml`
          
      - name: "🤖 Lint pipeline-service-reconcile.yaml"
        uses: docker://mydocker/platform-pipeline-service:latest
        with:
          args: lint /tmp/pipeline-services.yaml
```

It returns /tmp/pipeline-service.yaml doesn't exist

3. I tried to use directory to push files but it returns RUNTIME ERROR: multi mode: top-level object was a string, should be an object whose keys are filenames and values hold the JSON for that file.
  ```
- name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Jsonnet"
        uses: alexdglover/jsonnet-render@v2
        with:
          file: template.jsonnet
          output_dir: /tmp/
```
